name: CI

on:
  push:
    branches:
      - main  # Adjust this if you're using a different branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install python-dotenv  # Ensure dotenv is installed

      - name: Run application
        env:
          MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        run: python app.py  # Adjust if your entry point is different
