name: GitHub Action

on:
  push:
    branches:
      - ECommerce-Flask-Application
  pull_request:
    branches:
      - ECommerce-Flask-Application

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd="curl --silent --fail localhost:27017 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Run tests
        env:
          MONGODB_USERNAME: ${{ secrets.Ankit26114 }}
          MONGODB_PASSWORD: ${{ secrets.123Ankit }}
        run: |
          python -m unittest discover tests/

  # Optionally, add a "build" job if you want to run the Flask app after tests pass
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Run application
        env:
          MONGODB_USERNAME: ${{ secrets.Ankit26114 }}
          MONGODB_PASSWORD: ${{ secrets.123Ankit }}
        run: python app.py
