name: Github Action

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install python-dotenv  # Ensure dotenv is installed

      - name: Run application
        env:
          MONGODB_USERNAME: ${{ secrets.Ankit26114 }}  # Ensure these secret names are correct
          MONGODB_PASSWORD: ${{ secrets.123Ankit }}
        run: python app.py  # Adjust if your entry point is different
